<?php

namespace AppBundle\Repository;

/**
 * article_classRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class article_classRepository extends \Doctrine\ORM\EntityRepository
{

}
