<?php

namespace AppBundle\Repository;

/**
 * SingerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SingerRepository extends \Doctrine\ORM\EntityRepository
{
}
